name: p3l_k3_mobile
description: "Atma Kitchen's Mobile App"
publish_to: "none"
version: 0.0.4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_riverpod: ^2.4.9
  freezed: ^2.4.6
  gap: ^3.0.1
  hooks_riverpod: ^2.4.9
  riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_annotation: ^2.3.3
  logger: ^2.0.2+1
  google_fonts: ^6.2.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  auto_route: ^8.0.3
  tinycolor2: ^3.0.1
  lottie: ^3.1.0
  card_swiper: ^3.0.1
  flutter_animate: ^4.5.0
  el_tooltip: ^2.0.0
  font_awesome_flutter: ^10.7.0
  zoom_pinch_overlay: ^1.4.3
  dio: ^5.4.3+1
  toastification: ^2.0.0
  skeletonizer: ^1.1.2+1
  onesignal_flutter: ^5.2.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  dependency_validator: ^3.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  riverpod_lint: ^2.1.1
  very_good_analysis: ^5.1.0
  riverpod_generator: ^2.3.3
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/anim/
    - assets/pictures/

flutter_launcher_icons:
  image_path: "assets/logo/color.png"
  android:
    - adaptive_icon_background: "#ffffff"
    - adaptive_icon_foreground: "assets/logo/color.png"
  ios: true
